# Generated by Django 4.2.7 on 2023-11-28 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("actividadLimpieza", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuadrilla",
            name="id_usuario",
        ),
        migrations.AlterField(
            model_name="actividad",
            name="estado",
            field=models.CharField(
                choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                default="ACTIVO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="colonia",
            name="estado",
            field=models.CharField(
                choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                default="ACTIVO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cuadrilla",
            name="estado",
            field=models.CharField(
                choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                default="ACTIVO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cuadrilla",
            name="jefe_cuadrilla",
            field=models.ForeignKey(
                limit_choices_to={"rol": "JEFE DE CUADRILLA"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jefes_cuadrilla",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="estado",
            field=models.CharField(
                choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                default="ACTIVO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMINISTRADOR", "administrador"),
                    ("JEFE DE CUADRILLA", "jefe de cuadrilla"),
                    ("EMPLEADO", "empleado"),
                ],
                default="EMPLEADO",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="EmpleadoCuadrilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cuadrilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empleados",
                        to="actividadLimpieza.cuadrilla",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        limit_choices_to={"rol": "EMPLEADO"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("cuadrilla", "empleado")},
            },
        ),
    ]
